
# parsetab.py
# This file is automatically generated. Do not edit.
# pylint: disable=W,C,R
_tabversion = '3.10'

_lr_method = 'LALR'

_lr_signature = 'DIV ID IF LBRACE MINUS NUMBER PLUS RBRACE SEMI TIMES WITHwaeStart : wae SEMIwae : NUMBERwae : IDwae : LBRACE PLUS wae wae RBRACEwae : LBRACE MINUS wae wae RBRACEwae : LBRACE TIMES wae wae RBRACEwae : LBRACE DIV wae wae RBRACEwae : LBRACE IF wae wae wae RBRACEwae : LBRACE WITH wae wae wae RBRACE'
    
_lr_action_items = {'NUMBER':([0,3,4,7,8,9,10,11,12,13,14,15,16,17,18,23,24,25,26,27,28,31,32,],[3,-2,-3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,-4,-5,-6,-7,-8,-9,]),'ID':([0,3,4,7,8,9,10,11,12,13,14,15,16,17,18,23,24,25,26,27,28,31,32,],[4,-2,-3,4,4,4,4,4,4,4,4,4,4,4,4,4,4,-4,-5,-6,-7,-8,-9,]),'LBRACE':([0,3,4,7,8,9,10,11,12,13,14,15,16,17,18,23,24,25,26,27,28,31,32,],[5,-2,-3,5,5,5,5,5,5,5,5,5,5,5,5,5,5,-4,-5,-6,-7,-8,-9,]),'$end':([1,6,],[0,-1,]),'SEMI':([2,3,4,25,26,27,28,31,32,],[6,-2,-3,-4,-5,-6,-7,-8,-9,]),'RBRACE':([3,4,19,20,21,22,25,26,27,28,29,30,31,32,],[-2,-3,25,26,27,28,-4,-5,-6,-7,31,32,-8,-9,]),'PLUS':([5,],[7,]),'MINUS':([5,],[8,]),'TIMES':([5,],[9,]),'DIV':([5,],[10,]),'IF':([5,],[11,]),'WITH':([5,],[12,]),}

_lr_action = {}
for _k, _v in _lr_action_items.items():
   for _x,_y in zip(_v[0],_v[1]):
      if not _x in _lr_action:  _lr_action[_x] = {}
      _lr_action[_x][_k] = _y
del _lr_action_items

_lr_goto_items = {'waeStart':([0,],[1,]),'wae':([0,7,8,9,10,11,12,13,14,15,16,17,18,23,24,],[2,13,14,15,16,17,18,19,20,21,22,23,24,29,30,]),}

_lr_goto = {}
for _k, _v in _lr_goto_items.items():
   for _x, _y in zip(_v[0], _v[1]):
       if not _x in _lr_goto: _lr_goto[_x] = {}
       _lr_goto[_x][_k] = _y
del _lr_goto_items
_lr_productions = [
  ("S' -> waeStart","S'",1,None,None,None),
  ('waeStart -> wae SEMI','waeStart',2,'p_waeStart','WAEParser.py',8),
  ('wae -> NUMBER','wae',1,'p_wae_1','WAEParser.py',13),
  ('wae -> ID','wae',1,'p_wae_2','WAEParser.py',18),
  ('wae -> LBRACE PLUS wae wae RBRACE','wae',5,'p_wae_3','WAEParser.py',23),
  ('wae -> LBRACE MINUS wae wae RBRACE','wae',5,'p_wae_4','WAEParser.py',28),
  ('wae -> LBRACE TIMES wae wae RBRACE','wae',5,'p_wae_5','WAEParser.py',33),
  ('wae -> LBRACE DIV wae wae RBRACE','wae',5,'p_wae_6','WAEParser.py',38),
  ('wae -> LBRACE IF wae wae wae RBRACE','wae',6,'p_wae_7','WAEParser.py',43),
  ('wae -> LBRACE WITH wae wae wae RBRACE','wae',6,'p_wae_8','WAEParser.py',48),
]
